# Generated by Django 3.2.7 on 2021-09-27 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildable',
            name='displayname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='displayname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='displayname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')]),
        ),
    ]
